language: php

php:
  - 7.1

before_script:
  - composer update

script:
  - vendor/bin/phpunit
  - sonar-scanner

dist: trusty

addons:
  sonarcloud:
    organization: "kloud333-github"
    token:
      secure: eca01abf9f5364b5b90f105eb795e6d3005dd220

