language: php

php:
  - 7.1

dist: trusty

before_script:
  - composer install

script:
  - vendor/bin/phpunit
  - sonar-scanner

addons:
  sonarcloud:
    organization: "kloud333-github"
    token:
      secure: ba2c6a35be12fdd0e7113e6f42ec004e04a338e7

