language: php

php:
  - 7.1

before_script:
  - composer update



dist: trusty

addons:
  sonarcloud:
    organization: "kloud333-github"
    token:
      secure: ba2c6a35be12fdd0e7113e6f42ec004e04a338e7



script:
  - vendor/bin/phpunit
  - sonar-scanner